"""Ajout du champ  à User

Revision ID: 9b67241a6c99
Revises: 40bdb3642e16
Create Date: 2025-05-19 22:12:17.427461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b67241a6c99'
down_revision = '40bdb3642e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assistants',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.assistantId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'assistant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_assistants')
    # ### end Alembic commands ###
